<?php

namespace Xpressengine\Plugins\Board\Components\Widgets\Searching\Skins\Basic;

use Xpressengine\Skin\GenericSkin;

class BasicSearchingSkin extends GenericSkin
{
    protected static $path = 'board/components/Widgets/Searching/Skins/Basic';

    public function render()
    {
        return parent::render(); // TODO: Change the autogenerated stub
    }
}
